import { Bell } from "lucide-react";

export default function AlertsPage() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold text-white">Alerts</h1>
        <p className="mt-1 text-sm text-gray-500">
          Real-time notifications about changes to your attack surface.
        </p>
      </div>

      <div className="rounded-xl border border-dashed border-gray-800 bg-gray-900/40 p-8 text-center">
        <Bell className="mx-auto h-8 w-8 text-gray-600" />
        <h2 className="mt-3 text-sm font-medium text-white">
          No alerts yet
        </h2>
        <p className="mx-auto mt-1 max-w-sm text-sm text-gray-500">
          Alerts are generated by the monitoring engine (Step 9) once scans are running.
          Nothing to show here until that&apos;s built and a domain has been scanned.
        </p>
      </div>
    </div>
  );
}
